name: onyx-server
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - gunicorn
    - psycopg2-binary
    - django
    - djangorestframework
    - django-rest-knox
    - django-filter
    - django-cursor-pagination
    - django-query-tools
