name: metadb
channels:
  - defaults
dependencies:
  - gunicorn
  - pip
  - pip:
    - psycopg2-binary
    - django
    - djangorestframework
    - django-rest-knox
    - django-filter
    - django-model-utils
    - requests
    - pandas

