name: metadb
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - gunicorn
    - django
    - djangorestframework
    - django-rest-knox
    - django-filter
    - django-model-utils
    - django-cursor-pagination
    - celery
    - requests
    - pandas
