name: Django CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install poetry==1.7.0
        python -m poetry config virtualenvs.in-project true
        poetry env use ${{ matrix.python-version }}
        python -m poetry install --with test
    - name: Run Tests
      env:
        SECRET_KEY: super-duper-secret-key
        HOST_NAME: localhost
        DATABASE_NAME: db-not-found
        DATABASE_USER: user-not-found
      working-directory: ./onyx
      run: |
        python -m poetry run coverage run --source='.' manage.py test -v 2
        python -m poetry coverage report
