name: Run tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install poetry==1.7.0
        poetry config virtualenvs.in-project true
        poetry env use ${{ matrix.python-version }}
        poetry install --with test
    - name: Set up database
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres psql -c "CREATE DATABASE onyx OWNER root;"

    - name: Run Tests
      env:
        SECRET_KEY: super-duper-secret-key
        HOST_NAME: localhost
        DATABASE_NAME: onyx
        DATABASE_USER: root
      working-directory: ./onyx
      run: |
        poetry run coverage run --source='.' manage.py test -v 2
        poetry run coverage report
